# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Accounts.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_withdraw = QtWidgets.QRadioButton(self.centralwidget)
        self.button_withdraw.setGeometry(QtCore.QRect(80, 180, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_withdraw.setFont(font)
        self.button_withdraw.setObjectName("button_withdraw")
        self.actionGroup = QtWidgets.QButtonGroup(MainWindow)
        self.actionGroup.setObjectName("actionGroup")
        self.actionGroup.addButton(self.button_withdraw)
        self.button_deposit = QtWidgets.QRadioButton(self.centralwidget)
        self.button_deposit.setGeometry(QtCore.QRect(190, 180, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_deposit.setFont(font)
        self.button_deposit.setObjectName("button_deposit")
        self.actionGroup.addButton(self.button_deposit)
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(50, 380, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_submit.setFont(font)
        self.button_submit.setObjectName("button_submit")
        self.button_savings = QtWidgets.QRadioButton(self.centralwidget)
        self.button_savings.setGeometry(QtCore.QRect(40, 140, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_savings.setFont(font)
        self.button_savings.setObjectName("button_savings")
        self.accountGroup = QtWidgets.QButtonGroup(MainWindow)
        self.accountGroup.setObjectName("accountGroup")
        self.accountGroup.addButton(self.button_savings)
        self.button_checking = QtWidgets.QRadioButton(self.centralwidget)
        self.button_checking.setGeometry(QtCore.QRect(190, 140, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_checking.setFont(font)
        self.button_checking.setObjectName("button_checking")
        self.accountGroup.addButton(self.button_checking)
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(100, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        self.label_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_amount.setGeometry(QtCore.QRect(40, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_amount.setFont(font)
        self.label_amount.setObjectName("label_amount")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(40, 50, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(220, 380, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.label_details = QtWidgets.QLabel(self.centralwidget)
        self.label_details.setGeometry(QtCore.QRect(80, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_details.setFont(font)
        self.label_details.setText("")
        self.label_details.setObjectName("label_details")
        self.label_detailed_amount = QtWidgets.QLabel(self.centralwidget)
        self.label_detailed_amount.setGeometry(QtCore.QRect(50, 290, 121, 16))
        self.label_detailed_amount.setText("")
        self.label_detailed_amount.setObjectName("label_detailed_amount")
        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(50, 320, 121, 41))
        self.label_total.setText("")
        self.label_total.setWordWrap(True)
        self.label_total.setObjectName("label_total")
        self.label_used = QtWidgets.QLabel(self.centralwidget)
        self.label_used.setGeometry(QtCore.QRect(240, 290, 111, 16))
        self.label_used.setText("")
        self.label_used.setObjectName("label_used")
        self.label_sum = QtWidgets.QLabel(self.centralwidget)
        self.label_sum.setGeometry(QtCore.QRect(240, 330, 111, 16))
        self.label_sum.setText("")
        self.label_sum.setWordWrap(True)
        self.label_sum.setObjectName("label_sum")
        self.label_detailed_name = QtWidgets.QLabel(self.centralwidget)
        self.label_detailed_name.setGeometry(QtCore.QRect(50, 250, 121, 16))
        self.label_detailed_name.setText("")
        self.label_detailed_name.setObjectName("label_detailed_name")
        self.label_user_name = QtWidgets.QLabel(self.centralwidget)
        self.label_user_name.setGeometry(QtCore.QRect(240, 250, 111, 16))
        self.label_user_name.setText("")
        self.label_user_name.setWordWrap(True)
        self.label_user_name.setObjectName("label_user_name")
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(90, 250, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_message.setFont(font)
        self.label_message.setText("")
        self.label_message.setWordWrap(True)
        self.label_message.setObjectName("label_message")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(180, 50, 161, 21))
        self.input_name.setObjectName("input_name")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(180, 100, 161, 21))
        self.input_amount.setObjectName("input_amount")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_withdraw.setText(_translate("MainWindow", "Withdraw"))
        self.button_deposit.setText(_translate("MainWindow", "Deposit"))
        self.button_submit.setText(_translate("MainWindow", "SUBMIT"))
        self.button_savings.setText(_translate("MainWindow", "Savings Account"))
        self.button_checking.setText(_translate("MainWindow", "Checking Account"))
        self.label_main.setText(_translate("MainWindow", "Account Management"))
        self.label_amount.setText(_translate("MainWindow", "Amount of money"))
        self.label_name.setText(_translate("MainWindow", "Account name"))
        self.button_clear.setText(_translate("MainWindow", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

